Features/desafio 4
thallesfreitaszup/gg-fase-1 pull request #2
Opened 2019-10-23 20:19 UTC by thallesfreitaszup

2019-10-24 21:21 UTC, LG95 requested changes

2019-10-24 21:21 UTC, LG95 commented on gg-fase-1-master/firstSpring/src/main/java/com/zup/spring/service/FileService.java
> +			buffReader.close();
Pequise sobre fechamento de recursos em Java.

2019-10-24 21:21 UTC, LG95 commented on gg-fase-1-master/firstSpring/src/main/java/com/zup/spring/service/FileService.java
> +			buffWriter.close();
Pequise sobre fechamento de recursos em Java.

2019-10-24 21:21 UTC, LG95 commented on gg-fase-1-master/firstSpring/src/main/java/com/zup/spring/service/FileService.java
> +		int itemEncontrado = 0;
Porque não boolean?

2019-10-24 21:21 UTC, LG95 commented on gg-fase-1-master/firstSpring/src/main/java/com/zup/spring/service/FileService.java
> +			buffReader.close();
Pequise sobre fechamento de recursos em Java.

2019-10-24 21:21 UTC, LG95 commented on gg-fase-1-master/firstSpring/src/main/java/com/zup/spring/service/FileService.java
> +			buffWriter.close();
Pequise sobre fechamento de recursos em Java.

2019-10-24 21:21 UTC, LG95 commented on gg-fase-1-master/firstSpring/src/main/java/com/zup/spring/service/FileService.java
> +			}
Pequise sobre fechamento de recursos em Java.

2019-10-24 21:21 UTC, LG95 commented on gg-fase-1-master/firstSpring/src/main/java/com/zup/spring/service/FileService.java
> +			buffReader.close();
Pequise sobre fechamento de recursos em Java.

2019-10-25 12:09 UTC, thallesfreitaszup commented on gg-fase-1-master/firstSpring/src/main/java/com/zup/spring/service/FileService.java
> +		int itemEncontrado = 0;
É só uma mania que eu peguei de quando programava em C na faculdade kk,não tenho costume ainda de usar boolean.

2019-10-26 18:27 UTC, merged

2019-10-28 21:17 UTC, LG95 commented on gg-fase-1-master/firstSpring/src/main/java/com/zup/spring/service/FileService.java
> +		int itemEncontrado = 0;
De boa, falei para ir acustomando mesmo

2019-10-28 21:19 UTC, LG95 reviewed
Aprovado