Hotfix/desafio 3
thallesfreitaszup/gg-fase-1 pull request #3
Opened 2019-10-24 17:13 UTC by thallesfreitaszup

2019-10-24 18:01 UTC, LG95 requested changes
Vi que você comitou parte do desafio 4 nessa branch. Tente retirar esses commits.

2019-10-24 18:08 UTC, LG95 requested changes

2019-10-24 18:08 UTC, LG95 commented on gg-fase-1-master/request/src/main/java/com/br/zup/juniors/request/Service.java
> +	public static  HttpRequest criaRequest(String url,String tipo,StringBuilder dados) {
A criação do request estava muito parecida entre os três métodos?

2019-10-24 18:51 UTC, thallesfreitaszup commented on gg-fase-1-master/request/src/main/java/com/br/zup/juniors/request/Service.java
> +	public static  HttpRequest criaRequest(String url,String tipo,StringBuilder dados) {
Mudava pouca coisa,tipo a url ou o método(get,delete).Achei que você tinha sugerido o principio DRY com base nessa parte.

2019-10-26 18:17 UTC, merged

2019-10-28 21:21 UTC, LG95 commented on gg-fase-1-master/request/src/main/java/com/br/zup/juniors/request/Service.java
> +	public static  HttpRequest criaRequest(String url,String tipo,StringBuilder dados) {
Não foi baseado nisso não. Observa como está o código de chamada das URLs e tratamento de erro dessa chamada.