Features/desafio 5
thallesfreitaszup/gg-fase-1 pull request #9
Opened 2019-10-30 20:12 UTC by thallesfreitaszup

2019-11-04 22:24 UTC, LG95 requested changes

2019-11-04 22:24 UTC, LG95 commented on gg-fase-1-master/firstSpringJPA/src/main/java/com/zup/spring/service/PersistenciaService.java
> +		dados.setChave(chaveValor[0]);
Porque não fazer um constutor que recebe a chave e o valor?

2019-11-04 22:24 UTC, LG95 commented on gg-fase-1-master/firstSpringJPA/src/main/java/com/zup/spring/service/PersistenciaService.java
> +		String []chaveValor = string.split(":");
Essa operação recebe chave:valor?

2019-11-04 22:24 UTC, LG95 commented on gg-fase-1-master/firstSpringJPA/src/main/java/com/zup/spring/service/PersistenciaService.java
> +		this.dadosRepositorio.delete(dados);
Porque buscar antes de deletar?

2019-11-04 22:24 UTC, LG95 commented on gg-fase-1-master/firstSpringJPA/src/test/java/com/zup/spring/PersistenciaServiceTest.java
> +	public void testPersistencia(){
Descreva o objetivo deste teste e como ele realiza isso.

2019-11-04 22:24 UTC, LG95 commented on gg-fase-1-master/firstSpringJPA/src/test/java/com/zup/spring/PersistenciaServiceTest.java
> +		listaDados = this.persistenciaService.listarArquivo();
Para que essa chamada?

2019-11-04 22:24 UTC, LG95 commented on gg-fase-1-master/firstSpringJPA/src/test/java/com/zup/spring/PersistenciaServiceTest.java
> +		when(dadosRepositorio.save(dados1)).thenReturn(dados);
Essa configuração é algo que pode acontecer normalmente?

2019-11-04 22:24 UTC, LG95 commented on gg-fase-1-master/firstSpringJPA/src/test/java/com/zup/spring/PersistenciaServiceTest.java
> +		assertEquals(0,this.persistenciaService.listarArquivo().size());
Sem deletar esse assert falharia?

2019-11-05 13:27 UTC, thallesfreitaszup commented on gg-fase-1-master/firstSpringJPA/src/main/java/com/zup/spring/service/PersistenciaService.java
> +		dados.setChave(chaveValor[0]);
não pensei na hora,arrumei.

2019-11-05 18:37 UTC, LG95 requested changes
Favor responder as perguntas não tratadas como resposta por aqui.

2019-11-05 18:37 UTC, LG95 commented on gg-fase-1-master/firstSpringJPA/src/test/java/com/zup/spring/PersistenciaServiceTest.java
> +		assertEquals(1,this.persistenciaService.deletarItemArquivo("chave"));
Qual o objetivo deste teste?

2019-11-07 19:07 UTC, LG95 approved these changes
Mano, como o desafio 5 é outro e terá várias oportunidades para mexer com testes unitários, vamos encerrar esse aqui.

2019-11-07 19:30 UTC, merged